openapi: 3.0.0
info:
  version: 1.0.0
  title: OrderService API
  description: API for managing product orders and payment integrations.
paths:
  /orders:
    post:
      summary: Place a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  description: ID of the product to be ordered.
                quantity:
                  type: integer
                  description: Number of items to order.
      responses:
        '200':
          description: Order successfully placed.
        '400':
          description: Invalid input.
  /orders/{orderId}:
    get:
      summary: Retrieve details of a specific order
      parameters:
        - name: orderId
          in: path
          required: true
          description: Unique ID of the order.
          schema:
            type: string
      responses:
        '200':
          description: Order details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                  productId:
                    type: string
                  quantity:
                    type: integer
                  status:
                    type: string
                    enum: [placed, processed, delivered]
        '404':
          description: Order not found.
